/**
 * Strategic Watch & Market Radar Seed Data for Bridge Influence Module
 * Conçu pour Orange Cameroun & McCANN Douala/Yaoundé
 */

export const STRATEGIC_TYPES = {
  INFLUENCER: 'influencer',
  CAMPAIGN: 'campaign',
  COMPETITOR: 'competitor',
  PLATFORM: 'platform',
  TREND: 'trend',
  MEDIA: 'media',
  REGULATION: 'regulation',
  SECTOR: 'sector'
};

export const RELIABILITY_LEVELS = {
  A_OFFICIELLE: { code: 'A', label: 'Source officielle / Certifiée', score: 95, color: '#28A745', bg: '#E8F5E9' },
  B_VERIFIEE: { code: 'B', label: 'Donnée vérifiée & documentée', score: 85, color: '#0099FF', bg: '#E3F2FD' },
  C_SPECIALISEE: { code: 'C', label: 'Média ou cabinet spécialisé', score: 70, color: '#6C757D', bg: '#F1F3F5' },
  D_A_CONFIRMER: { code: 'D', label: 'Signal faible à confirmer', score: 50, color: '#FF7900', bg: '#FFF3E0' },
  E_RUMEUR: { code: 'E', label: 'Observation non vérifiée', score: 30, color: '#DC3545', bg: '#FFEBEE' },
};

export const CONFIDENCE_LEVELS = {
  CONFIRME: { id: 'Confirmé', label: 'Confirmé (100%)', badgeClass: 'tag-green' },
  PROBABLE: { id: 'Probable', label: 'Probable (~75%)', badgeClass: 'tag-blue' },
  ESTIMATION: { id: 'Estimation', label: 'Estimation qualifiée', badgeClass: 'tag-orange' },
  A_VERIFIER: { id: 'À vérifier', label: 'À vérifier', badgeClass: 'tag-yellow' },
  NON_RENSEIGNE: { id: 'Non renseigné', label: 'Non renseigné', badgeClass: 'tag-muted' },
};

export const ALERT_PRIORITIES = {
  BLOQUANT: { id: 'bloquant', label: 'Bloquant', rank: 5, color: '#721C24', bg: '#F8D7DA', border: '#F5C6CB' },
  CRITIQUE: { id: 'critique', label: 'Critique', rank: 4, color: '#DC3545', bg: '#FFEBEF', border: '#FFA8B6' },
  IMPORTANT: { id: 'important', label: 'Important', rank: 3, color: '#FF7900', bg: '#FFF3E0', border: '#FFCC80' },
  A_SURVEILLER: { id: 'a_surveiller', label: 'À surveiller', rank: 2, color: '#0070B8', bg: '#E1F5FE', border: '#B3E5FC' },
  INFORMATION: { id: 'information', label: 'Information', rank: 1, color: '#495057', bg: '#F8F9FA', border: '#E9ECEF' },
};

export const RBAC_ROLES = {
  admin: {
    id: 'admin',
    name: 'Administrateur',
    description: 'Configuration complète, connecteurs, règles d’alertes, imports et journal d’audit.',
    canConfigure: true,
    canEdit: true,
    canCreateInsight: true,
    canResolveAlerts: true,
    canViewSensitiveBudgets: true,
    canExport: true,
    canAccessAudit: true,
  },
  influence_manager: {
    id: 'influence_manager',
    name: 'Influence Manager',
    description: 'Création, qualification, pilotage opérationnel, watchlists, insights et recommandations.',
    canConfigure: true,
    canEdit: true,
    canCreateInsight: true,
    canResolveAlerts: true,
    canViewSensitiveBudgets: true,
    canExport: true,
    canAccessAudit: true,
  },
  cp_digital: {
    id: 'cp_digital',
    name: 'Chef de Projet Digital',
    description: 'Association aux campagnes, création de tâches, suivi des alertes et actions correctives.',
    canConfigure: false,
    canEdit: true,
    canCreateInsight: true,
    canResolveAlerts: true,
    canViewSensitiveBudgets: true,
    canExport: true,
    canAccessAudit: false,
  },
  web_analyst: {
    id: 'web_analyst',
    name: 'Digital Web Analyst',
    description: 'Analyse approfondie des signaux, benchmarks, contrôle qualité et génération de rapports.',
    canConfigure: false,
    canEdit: true,
    canCreateInsight: true,
    canResolveAlerts: false,
    canViewSensitiveBudgets: true,
    canExport: true,
    canAccessAudit: true,
  },
  content_cm: {
    id: 'content_cm',
    name: 'Content / Community Manager',
    description: 'Consultation des tendances plateformes, formats viraux et alertes de modération assignées.',
    canConfigure: false,
    canEdit: false,
    canCreateInsight: true,
    canResolveAlerts: false,
    canViewSensitiveBudgets: false,
    canExport: false,
    canAccessAudit: false,
  },
  financial_manager: {
    id: 'financial_manager',
    name: 'Financial Manager',
    description: 'Veille concurrentielle budgétaire et analyse ROI sans exposition de données personnelles.',
    canConfigure: false,
    canEdit: false,
    canCreateInsight: false,
    canResolveAlerts: false,
    canViewSensitiveBudgets: true,
    canExport: true,
    canAccessAudit: false,
  },
  client_lead: {
    id: 'client_lead',
    name: 'Client Digital Lead (Orange Cameroun)',
    description: 'Vue exécutive filtrée : tendances validées, insights et opportunités d’amplification.',
    canConfigure: false,
    canEdit: false,
    canCreateInsight: false,
    canResolveAlerts: false,
    canViewSensitiveBudgets: false,
    canExport: true,
    canAccessAudit: false,
    clientRestrictedView: true,
  }
};

export const INITIAL_COMPETITORS = [
  {
    id: 'COMP-MTN-CM',
    name: 'MTN Cameroun',
    category: 'Télécoms & Mobile Money',
    country: 'Cameroun',
    brands: ['MTN', 'MoMo', 'MTN Pulse', 'Yello Digital'],
    official_profiles: [
      { platform: 'facebook', handle: '@MTNCameroon', followers: '1.4M' },
      { platform: 'instagram', handle: '@mtncameroon', followers: '320K' },
      { platform: 'tiktok', handle: '@mtn_cameroun', followers: '280K' },
      { platform: 'x', handle: '@MTNCameroon', followers: '185K' },
      { platform: 'linkedin', handle: 'mtn-cameroon', followers: '110K' }
    ],
    monitored_keywords: ['MoMo', 'Yello', 'MTN Pulse', 'Internet Illimité MTN', 'Fibre MTN'],
    monitored_hashtags: ['#MTNPulse', '#YellowSummer', '#MoMoCameroun', '#DoItWithMoMo'],
    monitored_sources: ['Digital Business Africa', 'Investir au Cameroun', 'Pages Facebook créateurs'],
    status: 'actif',
    risk_level: 'élevé',
    threat_level: 'Directeur d’offres concurrentes agressives sur la jeunesse et les transferts MoMo',
    primary_creators_used: ['Muriel Blanche', 'Mani Bella', 'Ko-C (en alternance)', 'Cabrel Nanjip Legacy'],
    estimated_monthly_influence_budget: 35000000,
    budget_confidence: 'Estimation',
    budget_source: 'Hypothèse basée sur la grille tarifaire standard et 14 activations visibles / mois',
    key_mechanics: ['Challenges TikTok avec cash prize MoMo', 'Campagnes de co-branding avec artistes urbains', 'Live streamings sponsorisés'],
    notes: 'Priorité de surveillance 1 : Forte réactivité sur les offres data étudiantes et street activation.',
    last_activity_date: '2026-09-06'
  },
  {
    id: 'COMP-CAMTEL',
    name: 'Camtel (Blue)',
    category: 'Télécoms & FAI',
    country: 'Cameroun',
    brands: ['Blue', 'Blue Home', 'Blue Go', 'Camtel Corporate'],
    official_profiles: [
      { platform: 'facebook', handle: '@CamtelOfficial', followers: '450K' },
      { platform: 'instagram', handle: '@blue_camtel', followers: '95K' },
      { platform: 'tiktok', handle: '@blue_camtel', followers: '62K' },
      { platform: 'linkedin', handle: 'camtel-officiel', followers: '82K' }
    ],
    monitored_keywords: ['Blue Home', 'Camtel 4G', 'Fibre Camtel', 'Blue Go'],
    monitored_hashtags: ['#BlueCameroun', '#BlueHome', '#CamtelFibre', '#LeCamerounAvance'],
    monitored_sources: ['Cameroon Tribune', 'EcoMatin', 'CP Officiels Camtel'],
    status: 'actif',
    risk_level: 'moyen',
    threat_level: 'Positionnement fort sur la fibre résidentielle et offres data illimitées à bas coût',
    primary_creators_used: ['Ulrich Takam', 'Moustik Karismatik', 'Créateurs Tech Yaoundé'],
    estimated_monthly_influence_budget: 18000000,
    budget_confidence: 'Probable',
    budget_source: 'Appel d’offres publicisé ARMP et volume de 8 influenceurs actifs identifiés',
    key_mechanics: ['Placement de box fibre chez des créateurs lifestyle', 'Sketchs humoristiques Blue'],
    notes: 'Campagne agressive sur Douala Bonapriso et Yaoundé Bastos observée ces 3 dernières semaines.',
    last_activity_date: '2026-09-05'
  },
  {
    id: 'COMP-NEXTTEL',
    name: 'Nexttel',
    category: 'Télécoms',
    country: 'Cameroun',
    brands: ['Nexttel', 'Flybox Nexttel'],
    official_profiles: [
      { platform: 'facebook', handle: '@NexttelCameroun', followers: '380K' },
      { platform: 'instagram', handle: '@nexttelofficial', followers: '42K' }
    ],
    monitored_keywords: ['Nexttel Flybox', 'Forfait Nuit Nexttel', 'Promo Nexttel'],
    monitored_hashtags: ['#Nexttel', '#NexttelCM'],
    monitored_sources: ['Investir au Cameroun'],
    status: 'actif',
    risk_level: 'faible',
    threat_level: 'Activité influence ralentie, focalisation sur promotions SMS et affichage rural',
    primary_creators_used: ['Influenceurs régionaux Grand-Nord et Ouest'],
    estimated_monthly_influence_budget: 4500000,
    budget_confidence: 'Estimation',
    budget_source: 'Veille terrain agence et nombre réduit d’occurrences digitales',
    key_mechanics: ['Sponsoring ponctuel de concerts et foires régionales'],
    notes: 'Actuellement peu présent sur TikTok et Instagram en 2026.',
    last_activity_date: '2026-08-28'
  },
  {
    id: 'COMP-WAVE-FINTECH',
    name: 'Acteurs Fintech & Néo-Banques (Radar Émergent)',
    category: 'Fintech & Paiement Mobile',
    country: 'Cameroun / CEMAC',
    brands: ['Wave CEMAC (en déploiement)', 'Yup Legacy', 'TapTap Send', 'Smobilpay'],
    official_profiles: [
      { platform: 'facebook', handle: '@FintechCMWatch', followers: '85K' }
    ],
    monitored_keywords: ['Frais de transfert 0%', 'Paiement marchand QR code', 'Transfert d’argent diaspora'],
    monitored_hashtags: ['#FintechCameroun', '#SendMoneyToCameroon', '#TransfertGratuit'],
    monitored_sources: ['Jeune Afrique Économie', 'COBAC Bulletin', 'Techpoint Africa'],
    status: 'actif',
    risk_level: 'élevé',
    threat_level: 'Pression tarifaire sur les frais Orange Money et capture de flux diaspora',
    primary_creators_used: ['Diaspora camerounaise en France, Belgique et USA (créateurs TikTok)', 'Créateurs tech locaux'],
    estimated_monthly_influence_budget: 12000000,
    budget_confidence: 'Estimation',
    budget_source: 'Monitorage des codes promo de parrainage sur YouTube et TikTok',
    key_mechanics: ['Parrainage rémunéré', 'Tutoriels démo de transferts sans frais'],
    notes: 'Surveillance étroite des influenceurs diaspora recommandant les alternatives de transfert.',
    last_activity_date: '2026-09-04'
  }
];

export const INITIAL_WATCHLISTS = [
  {
    id: 'WL-01',
    name: 'Ambassadeurs Clés & Talents Star Orange Cameroun',
    owner: 'Influence Manager',
    visibility: 'organisation',
    active: true,
    description: 'Suivi permanent des talents sous contrat et des créateurs premium du pool Orange Cameroun.',
    filters: {
      type: ['influencer'],
      associated_talent_ids: ['TAL-carles_antonio', 'TAL-simplest_tuthi', 'TAL-queen_diva', '1', '2', '3', '4'],
      priority: ['bloquant', 'critique', 'important', 'a_surveiller']
    },
    notification_preferences: { email: true, in_app: true, instant_critique: true },
    thresholds: {
      engagement_drop_pct: 15,
      brand_safety_flag: true,
      competitor_mention_detected: true
    },
    item_count: 12
  },
  {
    id: 'WL-02',
    name: 'Radar Concurrentiel Télécoms & MoMo (MTN vs Blue)',
    owner: 'Direction Stratégique',
    visibility: 'equipe',
    active: true,
    description: 'Surveillance des campagnes, activations créateurs et offres agressives de MTN et Camtel Blue.',
    filters: {
      type: ['competitor', 'campaign'],
      associated_competitor_ids: ['COMP-MTN-CM', 'COMP-CAMTEL', 'COMP-WAVE-FINTECH']
    },
    notification_preferences: { email: false, in_app: true, instant_critique: true },
    thresholds: {
      budget_spike: true,
      new_creator_activation: true
    },
    item_count: 18
  },
  {
    id: 'WL-03',
    name: 'Tendances TikTok & Formats Vidéos Verticaux Cameroun',
    owner: 'Content / Community Manager',
    visibility: 'equipe',
    active: true,
    description: 'Détection des sons en tendance, challenges urbains Douala/Yaoundé et formats UGC viraux.',
    filters: {
      platform: ['tiktok', 'instagram'],
      type: ['trend', 'platform']
    },
    notification_preferences: { email: false, in_app: true, instant_critique: false },
    thresholds: {
      reach_spike_views: 300000
    },
    item_count: 9
  },
  {
    id: 'WL-04',
    name: 'Conformité Réglementaire, CNC & Publicité Responsable',
    owner: 'Digital Web Analyst',
    visibility: 'organisation',
    active: true,
    description: 'Suivi des décisions ARSEL, MINPOSTEL, CNC et des règles de transparence sur les posts sponsorisés.',
    filters: {
      type: ['regulation', 'media', 'sector']
    },
    notification_preferences: { email: true, in_app: true, instant_critique: true },
    thresholds: {
      regulatory_sanction_or_rule: true
    },
    item_count: 5
  },
  {
    id: 'WL-05',
    name: 'Créateurs Émergents & Micro-Talents à Fort Potentiel',
    owner: 'Influence & Traffic Manager',
    visibility: 'client_autorise',
    active: true,
    description: 'Repérage précoce de micro-influenceurs universitaires et créateurs tech à fort taux d’engagement.',
    filters: {
      type: ['influencer', 'trend']
    },
    notification_preferences: { email: false, in_app: true, instant_critique: false },
    thresholds: {
      engagement_rate_min: 7.5
    },
    item_count: 8
  }
];

export const INITIAL_WATCH_ITEMS = [
  {
    id: 'SW-2026-001',
    type: 'competitor',
    title: 'MTN Cameroun active 6 macro-créateurs sur TikTok pour sa rentrée « MTN Pulse 2026 »',
    summary: 'Lancement synchronisé d’un challenge musical avec Muriel Blanche et créateurs comédie. Récompense annoncée : 5 millions FCFA de cash prize MoMo et forfaits data 1 an.',
    content: 'Une offensive coordonnée a été détectée sur TikTok et Instagram. 6 créateurs majeurs affichent simultanément le hashtag #MTNPulse2026. L’analyse des premiers retours montre un engagement de 8.4% supérieur à leur moyenne habituelle. L’offre cible directement les étudiants et les jeunes professionnels avant la rentrée académique.',
    source_name: 'Radar Social Bridge / TikTok Monitor',
    source_url: 'https://tiktok.com/tag/MTNPulse2026',
    source_type: 'integration',
    published_at: '2026-09-06T14:30:00Z',
    collected_at: '2026-09-06T15:10:00Z',
    freshness_status: 'en_temps_reel',
    reliability_level: 'A_OFFICIELLE',
    relevance_score: 96,
    confidence_level: 'Confirmé',
    geographic_scope: 'Cameroun',
    platform: 'tiktok',
    themes: ['Télécoms', 'Challenge viral', 'Data Étudiants', 'MoMo'],
    keywords: ['MTN Pulse', 'Cash prize', 'Challenge', 'Rentrée'],
    sentiment_or_tone: 'dynamique_agressif',
    associated_talent_ids: [],
    associated_campaign_ids: ['CAMP-001', 'CAMP-002'],
    associated_competitor_ids: ['COMP-MTN-CM'],
    status: 'nouveau',
    alert_triggered: true,
    priority: 'critique',
    recommended_action: 'Accélérer la vague 2 de la campagne Orange Weekend avec des activations UGC interactives sur TikTok.',
    opportunity_or_risk: 'risk',
    created_by: 'Système Bridge Bot v2',
    created_at: '2026-09-06T15:10:00Z',
    updated_at: '2026-09-06T15:10:00Z'
  },
  {
    id: 'SW-2026-002',
    type: 'influencer',
    title: 'Signal Brand Safety : Polémique en direct sur TikTok impliquant un créateur ambassadeur',
    summary: 'Lors d’un live TikTok hier soir, des propos controversés sur un arbitrage sportif local ont suscité une vive altercation verbale. Le talent porte un t-shirt sans marque mais son compte est sous contrat actif Orange.',
    content: 'Le signal a été repéré suite à plus de 450 commentaires mentionnant ses partenariats de marque. Le live a réuni plus de 18 000 spectateurs simultanés. Aucun hashtag Orange n’a été cité, mais le risque d’assimilation par les internautes existe compte tenu de sa présence récente sur la campagne Orange Weekend.',
    source_name: 'Social Listening Watch / Webzine 237 Online',
    source_url: 'https://camerounweb.com/actu/live-controverse',
    source_type: 'rss',
    published_at: '2026-09-06T22:15:00Z',
    collected_at: '2026-09-07T06:30:00Z',
    freshness_status: 'a_jour',
    reliability_level: 'B_VERIFIEE',
    relevance_score: 92,
    confidence_level: 'Confirmé',
    geographic_scope: 'Cameroun',
    platform: 'tiktok',
    themes: ['Brand Safety', 'Modération', 'Réputation'],
    keywords: ['Live controverse', 'Bad buzz potentiel', 'Ambassadeur'],
    sentiment_or_tone: 'controverse',
    associated_talent_ids: ['1', 'TAL-carles_antonio'],
    associated_campaign_ids: ['CAMP-001'],
    associated_competitor_ids: [],
    status: 'a_analyser',
    alert_triggered: true,
    priority: 'bloquant',
    recommended_action: 'Briefing immédiat avec l’agent du talent, rappel de la clause de réserve et mise en pause temporaire de ses programmations de la semaine.',
    opportunity_or_risk: 'risk',
    created_by: 'Influence Watcher AI',
    created_at: '2026-09-07T06:30:00Z',
    updated_at: '2026-09-07T07:15:00Z'
  },
  {
    id: 'SW-2026-003',
    type: 'trend',
    title: 'Opportunité d’amplification : Le format « Storytime humoristique en Camfranglais » explose sur Instagram Reels',
    summary: 'Les micro-vidéos narratives de 45 secondes racontant des anecdotes du quotidien en Camfranglais génèrent 3,4x plus de partages organiques à Douala et Yaoundé que les vidéos promotionnelles classiques.',
    content: 'Une analyse sur 120 publications de créateurs camerounais au cours du mois montre que les formats conversationnels de type « Tu savais que... » ou saynète de quartier surpassent largement les bannières statiques. Le taux d’achèvement de visionnage atteint 78% contre 32% sur les spots institutionnels.',
    source_name: 'Étude Insights Média McCANN Digital Lab',
    source_url: 'https://mccann.cm/lab/reels-camfranglais-2026',
    source_type: 'manual',
    published_at: '2026-09-05T10:00:00Z',
    collected_at: '2026-09-05T10:00:00Z',
    freshness_status: 'recent',
    reliability_level: 'A_OFFICIELLE',
    relevance_score: 88,
    confidence_level: 'Confirmé',
    geographic_scope: 'Cameroun',
    platform: 'instagram',
    themes: ['Formats de contenu', 'UGC', 'Camfranglais', 'Engagement'],
    keywords: ['Storytime', 'Reels', 'Virale', 'Camfranglais'],
    sentiment_or_tone: 'positif',
    associated_talent_ids: ['TAL-simplest_tuthi', '3', '4'],
    associated_campaign_ids: ['CAMP-002', 'CAMP-003'],
    associated_competitor_ids: [],
    status: 'transforme_en_insight',
    alert_triggered: false,
    priority: 'important',
    recommended_action: 'Co-créer 3 storytimes avec Simplest Tuthi et Marie-Claire Bella autour des usages réels d’Orange Money en marché ouvert.',
    opportunity_or_risk: 'opportunity',
    created_by: 'Sarah M. (Web Analyst)',
    created_at: '2026-09-05T10:00:00Z',
    updated_at: '2026-09-06T11:00:00Z'
  },
  {
    id: 'SW-2026-004',
    type: 'regulation',
    title: 'MINPOSTEL & CNC : Nouvelles directives relatives à l’identification des partenariats commerciaux',
    summary: 'Rappel officiel de l’obligation d’afficher distinctement la mention #CollaborationCommerciale ou #Publicite sur tous les contenus rémunérés en ligne au Cameroun.',
    content: 'Le Ministère des Postes et Télécommunications et le Conseil National de la Communication prévoient des contrôles aléatoires sur les comptes des influenceurs cumulant plus de 50 000 abonnés. Les marques commanditaires encourent une co-responsabilité en cas d’omission intentionnelle de la nature sponsorisée du contenu.',
    source_name: 'Communiqué Conjoint MINPOSTEL / CNC N°2026-08',
    source_url: 'https://minpostel.gov.cm/communique-influence-2026',
    source_type: 'api',
    published_at: '2026-09-04T16:00:00Z',
    collected_at: '2026-09-04T17:30:00Z',
    freshness_status: 'a_jour',
    reliability_level: 'A_OFFICIELLE',
    relevance_score: 95,
    confidence_level: 'Confirmé',
    geographic_scope: 'Cameroun',
    platform: 'multi',
    themes: ['Législation', 'Conformité', 'Transparence', 'Mentions Légales'],
    keywords: ['MINPOSTEL', 'CNC', 'Sponsoring', 'Réglementation'],
    sentiment_or_tone: 'reglementaire',
    associated_talent_ids: [],
    associated_campaign_ids: ['CAMP-001', 'CAMP-002', 'CAMP-003'],
    associated_competitor_ids: [],
    status: 'lu',
    alert_triggered: true,
    priority: 'important',
    recommended_action: 'Mettre à jour immédiatement la check-list de validation des livrables pour refuser tout contenu sans le hashtag #PartenariatOrange ou #CollabOrange.',
    opportunity_or_risk: 'risk',
    created_by: 'Alexandre T. (Legal & Ops)',
    created_at: '2026-09-04T17:30:00Z',
    updated_at: '2026-09-05T09:00:00Z'
  },
  {
    id: 'SW-2026-005',
    type: 'campaign',
    title: 'Surperformance remarquable : Le Reel Orange Money de Simplest Tuthi dépasse de +185% le benchmark',
    summary: 'Avec 248 000 vues organiques en 72 heures et un taux d’engagement de 9.1% (médiane campagne : 4.2%), la publication est le contenu le plus efficace du trimestre.',
    content: 'Le contenu a bénéficié d’un reach algorithmique favorisé par un fort taux de rediffusion et 1 420 commentaires qualifiés. Les questions des utilisateurs portent directement sur les plafonds de retrait sans frais. Une réelle opportunité de boost payant existe pour transformer ce reach organique en acquisition directe.',
    source_name: 'Performance Analytics Bridge Engine',
    source_url: 'https://instagram.com/simplest_tuthi/reel/C8991288',
    source_type: 'integration',
    published_at: '2026-09-05T18:00:00Z',
    collected_at: '2026-09-06T08:00:00Z',
    freshness_status: 'a_jour',
    reliability_level: 'A_OFFICIELLE',
    relevance_score: 91,
    confidence_level: 'Confirmé',
    geographic_scope: 'Cameroun',
    platform: 'instagram',
    themes: ['Campagne Orange', 'Surperformance', 'Orange Money', 'Amplification'],
    keywords: ['Surperformance', 'Simplest Tuthi', 'Benchmark', 'Vues'],
    sentiment_or_tone: 'tres_positif',
    associated_talent_ids: ['TAL-simplest_tuthi', '2'],
    associated_campaign_ids: ['CAMP-001'],
    associated_competitor_ids: [],
    status: 'a_analyser',
    alert_triggered: true,
    priority: 'important',
    recommended_action: 'Proposer au client Orange Cameroun une amplification média sponsorisée (Dark Post Meta) avec un budget test de 1,5M FCFA.',
    opportunity_or_risk: 'opportunity',
    created_by: 'Système Bridge Analytics',
    created_at: '2026-09-06T08:00:00Z',
    updated_at: '2026-09-06T08:30:00Z'
  },
  {
    id: 'SW-2026-006',
    type: 'competitor',
    title: 'Camtel Blue déploie une campagne d’affichage et d’influenceurs B2C « Blue Home Illimité »',
    summary: 'Prise de parole agressive de Camtel sur les forfaits fibre domestique à 15 000 FCFA/mois. 4 comédiens digitaux de Yaoundé ont publié des vidéos d’installation de box.',
    content: 'Camtel mise sur des démonstrations en conditions réelles (téléchargement de séries, jeux en ligne sans latence) pour attaquer les offres Flybox d’Orange et de MTN. L’estimation budgétaire globale de la vague d’influence est évaluée entre 12 et 18 millions FCFA sur 45 jours.',
    source_name: 'Revue Digitale Cameroun / Facebook Ad Library',
    source_url: 'https://facebook.com/ads/library/?active_status=all&ad_type=all&country=CM&view_all_page_id=CamtelOfficial',
    source_type: 'integration',
    published_at: '2026-09-03T11:20:00Z',
    collected_at: '2026-09-03T14:00:00Z',
    freshness_status: 'recent',
    reliability_level: 'B_VERIFIEE',
    relevance_score: 82,
    confidence_level: 'Probable',
    geographic_scope: 'Cameroun',
    platform: 'facebook',
    themes: ['Fibre Optique', 'Home Internet', 'Concurrent Direct'],
    keywords: ['Blue Home', 'Fibre', 'Camtel', 'Concurrence'],
    sentiment_or_tone: 'neutre_engage',
    associated_talent_ids: [],
    associated_campaign_ids: [],
    associated_competitor_ids: ['COMP-CAMTEL'],
    status: 'lu',
    alert_triggered: false,
    priority: 'a_surveiller',
    recommended_action: 'Monitorer les retours clients sous les publications Camtel concernant la stabilité réelle du service dans les quartiers cibles.',
    opportunity_or_risk: 'risk',
    created_by: 'Veille Concurrentielle Bot',
    created_at: '2026-09-03T14:00:00Z',
    updated_at: '2026-09-03T14:00:00Z'
  },
  {
    id: 'SW-2026-007',
    type: 'influencer',
    title: 'Détection d’anomalie d’audience : Hausse subite de +45K abonnés en 48h chez un candidat d’activation',
    summary: 'Le compte d’un créateur lifestyle présélectionné pour la campagne jeunesse présente une courbe anormale sans publication virale associée. Suspicion de faux abonnés achetés.',
    content: 'L’analyse du profil montre 45 000 nouveaux followers en 2 jours, provenant majoritairement de comptes sans photo de profil ni publications basés hors CEMAC (zones Asie/Moyen-Orient). Le ratio d’engagement est tombé mécaniquement de 4.8% à 1.1%. Recommandation formelle d’audit avant toute contractualisation.',
    source_name: 'Outil de détection de fraude d’audience Bridge v1',
    source_url: '',
    source_type: 'api',
    published_at: '2026-09-06T09:00:00Z',
    collected_at: '2026-09-06T09:15:00Z',
    freshness_status: 'a_jour',
    reliability_level: 'B_VERIFIEE',
    relevance_score: 87,
    confidence_level: 'À vérifier',
    geographic_scope: 'Cameroun',
    platform: 'instagram',
    themes: ['Fraude d’audience', 'Qualité des données', 'Sélection Talent'],
    keywords: ['Faux abonnés', 'Bots', 'Contrôle qualité'],
    sentiment_or_tone: 'negatif',
    associated_talent_ids: ['TAL-queen_diva'],
    associated_campaign_ids: [],
    associated_competitor_ids: [],
    status: 'nouveau',
    alert_triggered: true,
    priority: 'critique',
    recommended_action: 'Demander les captures d’écran natives d’Instagram Insights (répartition géographique et abonnements récents) sous 48h.',
    opportunity_or_risk: 'risk',
    created_by: 'Data Quality Watchdog',
    created_at: '2026-09-06T09:15:00Z',
    updated_at: '2026-09-06T09:15:00Z'
  },
  {
    id: 'SW-2026-008',
    type: 'platform',
    title: 'Mise à jour algorithme Meta : Pénalisation des vidéos contenant des filigranes tiers (TikTok / CapCut)',
    summary: 'Meta confirme officiellement que les Reels contenant le filigrane TikTok ou le logo CapCut verront leur diffusion restreinte dans l’onglet Explorer d’Instagram et Facebook.',
    content: 'La mise à jour déploie un système de reconnaissance visuelle automatisé qui rétrograde la visibilité des formats recyclés sans montage natif. Les influenceurs qui repostent leurs vidéos TikTok brutes sur Facebook et Instagram perdront jusqu’à 65% de reach organique non abonné.',
    source_name: 'Meta for Creators Newsroom Official',
    source_url: 'https://creators.instagram.com/blog/reels-algorithm-update-watermarks',
    source_type: 'api',
    published_at: '2026-09-02T15:00:00Z',
    collected_at: '2026-09-02T16:00:00Z',
    freshness_status: 'recent',
    reliability_level: 'A_OFFICIELLE',
    relevance_score: 94,
    confidence_level: 'Confirmé',
    geographic_scope: 'Global',
    platform: 'instagram',
    themes: ['Algorithme', 'Meta', 'Formats', 'Qualité de diffusion'],
    keywords: ['Filigrane', 'CapCut', 'TikTok watermark', 'Reels'],
    sentiment_or_tone: 'neutre',
    associated_talent_ids: [],
    associated_campaign_ids: ['CAMP-001', 'CAMP-002'],
    associated_competitor_ids: [],
    status: 'transforme_en_insight',
    alert_triggered: true,
    priority: 'important',
    recommended_action: 'Ajouter une règle contractuelle stricte exigeant la fourniture de fichiers MP4 natifs nettoyés sans aucun filigrane d’application tierce.',
    opportunity_or_risk: 'opportunity',
    created_by: 'Platform Tech Watch',
    created_at: '2026-09-02T16:00:00Z',
    updated_at: '2026-09-03T10:00:00Z'
  }
];

export const INITIAL_STRATEGIC_ALERTS = [
  {
    id: 'ALT-2026-001',
    watch_item_id: 'SW-2026-002',
    title: 'Brand Safety : Risque de réputation sur talent ambassadeur actif',
    alert_type: 'brand_safety',
    priority: 'bloquant',
    status: 'en_cours',
    trigger_rule: 'Détection de controverse live dépassant 400 mentions négatives',
    confidence_level: 'Confirmé',
    recommended_action: 'Contacter d’urgence l’agent du talent et bloquer la diffusion du post sponsorisé programmé pour demain 18h.',
    assigned_to: 'Influence Manager',
    due_at: '2026-09-07T14:00:00Z',
    resolved_at: null,
    resolution_note: '',
    created_at: '2026-09-07T06:35:00Z',
    comments: [
      { author: 'Influence Manager', text: 'Appel en cours avec le manager du créateur. Il confirme l’incident et rédige un mot d’apaisement.', date: '2026-09-07T07:15:00Z' }
    ]
  },
  {
    id: 'ALT-2026-002',
    watch_item_id: 'SW-2026-001',
    title: 'Attaque concurrentielle : Campagne agressive MTN Pulse 2026 sur TikTok',
    alert_type: 'competitor_activation',
    priority: 'critique',
    status: 'nouveau',
    trigger_rule: 'Plus de 4 créateurs majeurs activés simultanément avec hashtag concurrent direct',
    confidence_level: 'Confirmé',
    recommended_action: 'Organiser un point stratégique rapide avec l’équipe McCANN Brand & Media pour riposte digitale.',
    assigned_to: 'Chef de Projet Digital',
    due_at: '2026-09-08T10:00:00Z',
    resolved_at: null,
    resolution_note: '',
    created_at: '2026-09-06T15:15:00Z',
    comments: []
  },
  {
    id: 'ALT-2026-003',
    watch_item_id: 'SW-2026-007',
    title: 'Fraude d’audience présumée : Pic artificiel d’abonnés (+45K followers suspects)',
    alert_type: 'audience_anomaly',
    priority: 'critique',
    status: 'nouveau',
    trigger_rule: 'Croissance de followers > 10% en 48h sans contenu viral associé',
    confidence_level: 'À vérifier',
    recommended_action: 'Suspendre l’envoi du contrat cadre et exiger le certificat d’authenticité des métriques.',
    assigned_to: 'Digital Web Analyst',
    due_at: '2026-09-09T18:00:00Z',
    resolved_at: null,
    resolution_note: '',
    created_at: '2026-09-06T09:20:00Z',
    comments: []
  },
  {
    id: 'ALT-2026-004',
    watch_item_id: 'SW-2026-005',
    title: 'Opportunité d’amplification : Reel Orange Money en très forte surperformance (+185%)',
    alert_type: 'amplification_opportunity',
    priority: 'important',
    status: 'en_cours',
    trigger_rule: 'Taux d’engagement > 200% de la médiane de campagne',
    confidence_level: 'Confirmé',
    recommended_action: 'Soumettre la note d’opportunité d’amplification payante au Client Digital Lead.',
    assigned_to: 'Traffic Manager',
    due_at: '2026-09-08T16:00:00Z',
    resolved_at: null,
    resolution_note: '',
    created_at: '2026-09-06T08:15:00Z',
    comments: [
      { author: 'Traffic Manager', text: 'Proposition média en cours de chiffrage (budget 1.5M FCFA pour 400K impressions supplémentaires).', date: '2026-09-06T11:45:00Z' }
    ]
  },
  {
    id: 'ALT-2026-005',
    watch_item_id: 'SW-2026-004',
    title: 'Conformité légale : Obligation des mentions sponsorisées CNC/MINPOSTEL',
    alert_type: 'regulatory_compliance',
    priority: 'important',
    status: 'resolu',
    trigger_rule: 'Nouvelle directive légale sectorielle applicable aux campagnes en cours',
    confidence_level: 'Confirmé',
    recommended_action: 'Mise à jour des briefs et ajout de la mention obligatoire dans le template de contrat.',
    assigned_to: 'Influence Manager',
    due_at: '2026-09-05T12:00:00Z',
    resolved_at: '2026-09-05T11:30:00Z',
    resolution_note: 'Tous les créateurs sous contrat ont reçu l’avenant et les consignes pour intégrer le hashtag officiel #PartenariatOrange.',
    created_at: '2026-09-04T17:40:00Z',
    comments: []
  }
];

export const INITIAL_COLLECTION_RUNS = [
  {
    id: 'RUN-2026-09-07-01',
    source: 'Multi-sources (APIs Officielles + RSS + Social Listening)',
    started_at: '2026-09-07T07:45:00Z',
    finished_at: '2026-09-07T07:46:12Z',
    status: 'succès',
    rows_collected: 42,
    rows_created: 3,
    rows_updated: 7,
    rows_skipped: 32,
    errors: [],
    triggered_by: 'CRON_AUTOMATIQUE_15MIN',
    duration_seconds: 72
  },
  {
    id: 'RUN-2026-09-06-04',
    source: 'TikTok & Meta Ad Library Connectors',
    started_at: '2026-09-06T20:00:00Z',
    finished_at: '2026-09-06T20:01:05Z',
    status: 'succès',
    rows_collected: 28,
    rows_created: 2,
    rows_updated: 5,
    rows_skipped: 21,
    errors: [],
    triggered_by: 'CRON_AUTOMATIQUE_15MIN',
    duration_seconds: 65
  },
  {
    id: 'RUN-2026-09-06-03',
    source: 'MINPOSTEL & Veille Réglementaire Crawler',
    started_at: '2026-09-06T12:00:00Z',
    finished_at: '2026-09-06T12:00:34Z',
    status: 'succès',
    rows_collected: 6,
    rows_created: 0,
    rows_updated: 1,
    rows_skipped: 5,
    errors: [],
    triggered_by: 'Sarah M. (Manuel)',
    duration_seconds: 34
  }
];
